### ISSUE TITLE
RIB Compiler and Record Field Type Mismatch

### ISSUE THREAD

**Issue by Nanashi-lab** [golemcloud/golem#1490]
**Description:**

A RIB script fails to pass records properly to worker executor, causes field type mismatch at runtime. 

The RIB script compiles successfully and the adding the API succeeds. However, when the API is invoked, causes field type mismatch at runtime. 

**How to replicate**

This is the rib expression, it is for shopping-cart add-item function

```
response: |-
    let quantity: u32 = request.body.quantity;
    let product_id: string = request.body.product-id;
    let name: string = request.body.name;
    let price: f32 = request.body.price;
    let input = {price: price, product-id: product_id, name: name, quantity: quantity};
    let result = golem:shoppingcart/api.{add-item}(input);
     {status: 200: u64, body: "Item added"}
worker-name: |-
  "badworker-shopping-cart"
```

Input - 
``` json
{
  "quantity": 3,
  "product-id": "12345",
  "name": "pizza",
  "price": 21.0
}
```

Looking at the oplog, this is what is passed. 

```json
{
   "name": 21,                    
   "price": "12345",
   "product-id": "pizza",
   "quantity": 3
}
```

The function signature expects `name` to be a string (`Str`) according to the interface definition. The RIB script expects string `name` field from the request body as a string, however it is being passed as number.

Unedited Oplog

```json
{ "invocation": { "full_function_name": "golem:shoppingcart/api.{add-item}", "function_input": [ { "typ": { "fields": [ { "name": "product-id", "typ": { "type": "Str" } }, { "name": "name", "typ": { "type": "Str" } }, { "name": "price", "typ": { "type": "F32" } }, { "name": "quantity", "typ": { "type": "U32" } } ], "type": "Record" }, "value": { "name": 21, "price": "12345", "product-id": "pizza", "quantity": 3 } } ], "idempotency_key": "4b3fb269-2cf2-4d59-8a45-b764a451703f", "invocation_context": [ [ { "attributes": { "request.method": { "type": "String", "value": "GET" }, "request.remote_addr": { "type": "String", "value": "socket://127.0.0.1:49394" }, "request.uri": { "type": "String", "value": "/v0.0.1/bad-add-item" } }, "inherited": false, "linked_context": null, "parent_id": null, "span_id": "5a62aae758e7fce8", "start": "2025-04-06T11:25:28.684Z", "type": "LocalSpan" } ] ], "trace_id": "d56992aad0a2403481e90195df4a31c2", "trace_states": [], "type": "ExportedFunction" }, "timestamp": "2025-04-06T11:25:29.023Z", "type": "PendingWorkerInvocation" 
```

-------------------------------------------------------

Another example 

This is for todo-list, function add, here we only as title as input, 

```rib
response: |-
  let title: string = request.body.title;
  let result = golem:todolist/api.{add}({title: title, priority: high, deadline: none});
  {status: 200: u64, body: "Success"}
worker-name: |-
  "badworker-todo-list-1"
```

When I invoke the Api, Error 

```
Runtime error: Parameter type mismatch: in $.title expected string, got option
```

This indicates that the `title` field, which is expected to be a string, is being received as an `option` type (likely `Option<String>`).

--------------------------------------------------------

Both these error only happen when rib handles the record direclty, The following works fine. 

```
  let input = request.body.input;
  let result = golem:todolist/api.{add}(input);
```

or 

```
  let input = request.body.input;
  let result = golem:shoppingcart/api.{add-item}(input);
```

--------------------------------------------------------

**Location (Suspected):**

The problem likely exists in the RIB compiler's code, specifically within:

`golem-rib/src/rib_interpreter.rs` in the functions

*   `run_create_record_instruction`
*   `run_update_record_instruction`

**Comment by afsalthaj** [comment]
This is already fixed in main branch, and Rib now stick on to the order of field names and stick on to the original AnalysedType

**Comment by Nanashi-lab** [comment]
@afsalthaj Can you open this again. I am working with dev latest, I no longer get the error for todo-list, but still get the error for shopping cart. 

```
{ "invocation": { "full_function_name": "golem:shoppingcart-exports/golem-shoppingcart-api.{add-item}", "function_input": [ { "typ": { "fields": [ { "name": "product-id", "typ": { "type": "Str" } }, { "name": "name", "typ": { "type": "Str" } }, { "name": "price", "typ": { "type": "F32" } }, { "name": "quantity", "typ": { "type": "U32" } } ], "type": "Record" }, "value": { "name": "12345", "price": "pizza", "product-id": 21, "quantity": 3 } } ], "idempotency_key": "3eff4359-4d41-47df-8d02-3389cdafae08", "invocation_context": [ [ { "attributes": { "request.method": { "type": "String", "value": "GET" }, "request.remote_addr": { "type": "String", "value": "socket://127.0.0.1:40704" }, "request.uri": { "type": "String", "value": "/v0.0.1/bad-add-item" } }, "inherited": false, "linked_context": null, "parent_id": null, "span_id": "3df1597c70a838a6", "start": "2025-04-08T05:19:43.547Z", "type": "LocalSpan" } ] ], "trace_id": "1554db0a1e14401a88da0c693c06eebb", "trace_states": [], "type": "ExportedFunction" }, "timestamp": "2025-04-08T05:19:43.567Z", "type": "PendingWorkerInvocation" }
```

on a input of 

```json
{
  "product-id": "12345",
  "name": "pizza",
  "price": 21.0,
  "quantity": 3
}
```

**Comment by Nanashi-lab** [comment]
I tested this with both worker-name and first class worker, both fail with error below - shopping-cart is the latest shopping-cart example from `golem-cli `

` Previous invocation failed: Parameter type mismatch: in $.product-id expected string, got f32`

**Comment by Nanashi-lab** [comment]
```
║ Exports:
║   golem:delayecho/api.{echo-product}(product: record { id: u32, label: string, price: f32, quantity: u32 }) -> record { id: u32, label: string, price:
║      f32, quantity: u32 }
║   golem:delayecho/api.{echo-point3d}(point: record { x: f32, y: f32, z: f32, is-valid: bool, description: string, id: u32 }) -> record { x: f32, y:
║      f32, z: f32, is-valid: bool, description: string, id: u32 }
║   golem:delayecho/api.{echo-rectangle}(rect: record { width: u32, height: u32, area: f32, is-square: bool, color: string }) -> record { width: u32,
║      height: u32, area: f32, is-square: bool, color: string }
║   golem:delayecho/api.{echo-user-profile}(profile: record { name: string, age: u32, weight: f32, height: f32, nickname: option<string> }) -> record
║      { name: string, age: u32, weight: f32, height: f32, nickname: option<string> }
```

I tried replicating this error, but failed with all the functions above, Error for shopping-cart error persists for some reason. I am going to chalk this up to edge case. 

![Image](https://github.com/user-attachments/assets/fd6cf0cd-ce79-4c75-80b7-8744b0a7c435)
